### PR TITLE
mssql support

### LINKED ISSUE #3: MSSQL support
Even though I wanted to work on introducing priorities within one worker thread as we discussed in #1, the support for MSSQL got higher priority for us. So I focused on implementing mssql driver for db-queue.

So far, I have managed to implement the main classes: `MssqlQueueDao`, `MssqlQueuePickTaskDao`, and accompanying test classes. However, I want to clear out a couple of things before I make the PR:

- are you willing to accept a PR to support MSSQL directly in `db-queue`?
- **a: if yes**, how should we manage the databases in tests? right now, embedded postgres is used. However, that can't be the case for mssql. Should we assume that both of them will be executed externally? (via docker in case of travis-ci).
- **b: if no**, because of the way that `DatabaseDialect` is implemented and used, users of library can not add support for other databases. I think we need to have an implementation registry of sort so dialects can be added dynamically.

### PR DESCRIPTION
**Pull request by everplays**
fixes #3.

### CODE REVIEW

**Comment by everplays** [comment]
Hey @f0y, as you can see, I have a very rough implementation so far but unfortunately I can't get the library to build: neither locally nor on travis because of dependency issues. Currently, my best guess is that the new dependency, `testcontainers`, is not available in the repositories (mirrors at nexus.yamoney.ru) that are specified for the project. I tried to fiddle with repositories but no success.

Also, locally, I can't do anything with gradle:

```
⋊> ~/w/b/db-queue on mssql-support  ./gradlew-public

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'db-queue'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve ru.yandex.money.gradle.plugins:yamoney-library-project-plugin:4.+.
     Required by:
         project :
      > Failed to list versions for ru.yandex.money.gradle.plugins:yamoney-library-project-plugin.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/gradle-plugins/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/gradle-plugins/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/gradle-plugins/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
                  > nexus.yamoney.ru: Name or service not known
      > Failed to list versions for ru.yandex.money.gradle.plugins:yamoney-library-project-plugin.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/thirdparty/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/thirdparty/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/thirdparty/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.gradle.plugins:yamoney-library-project-plugin.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/central/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/central/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/central/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.gradle.plugins:yamoney-library-project-plugin.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/releases/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/releases/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/releases/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.gradle.plugins:yamoney-library-project-plugin.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/jcenter.bintray.com/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/jcenter.bintray.com/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/jcenter.bintray.com/ru/yandex/money/gradle/plugins/yamoney-library-project-plugin/maven-metadata.xml'.
                  > nexus.yamoney.ru
   > Could not resolve ru.yandex.money.platform:yamoney-libraries-dependencies:4.+.
     Required by:
         project :
      > Failed to list versions for ru.yandex.money.platform:yamoney-libraries-dependencies.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/gradle-plugins/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/gradle-plugins/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/gradle-plugins/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.platform:yamoney-libraries-dependencies.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/thirdparty/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/thirdparty/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/thirdparty/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.platform:yamoney-libraries-dependencies.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/central/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/central/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/central/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.platform:yamoney-libraries-dependencies.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/releases/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/releases/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/releases/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
                  > nexus.yamoney.ru
      > Failed to list versions for ru.yandex.money.platform:yamoney-libraries-dependencies.
         > Unable to load Maven meta-data from https://nexus.yamoney.ru/repository/jcenter.bintray.com/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml.
            > Could not get resource 'https://nexus.yamoney.ru/repository/jcenter.bintray.com/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
               > Could not GET 'https://nexus.yamoney.ru/repository/jcenter.bintray.com/ru/yandex/money/platform/yamoney-libraries-dependencies/maven-metadata.xml'.
                  > nexus.yamoney.ru

````

**Comment by f0y** [comment]
I see that all dependencies are resolved on travis. There is issue with compilation:
 ```
Compiling with JDK Java compiler API.
/home/travis/build/yandex-money-tech/db-queue/src/test/java/ru/yandex/money/common/dbqueue/utils/QueueDatabaseInitializer.java:9: error: cannot find symbol
import org.testcontainers.containers.MSSQLServerContainerProvider;
                                    ^
  symbol:   class MSSQLServerContainerProvider
  location: package org.testcontainers.containers
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

You should execute locally `./gradlew-public -b build-public.gradle build` command as stated in .travis.yml.
I'm sorry for such a mess with build infrastructure.

**Comment by f0y** [comment]
Let me know when all is ok from your point of view. I will move changes to our private repo.

**Comment by everplays** [comment]
True, apparently, the modules that support each database have to be added separately as dependency for `testcontainers` to work. I'll give you a ping when I'm finished with the implementation.

**Comment by everplays** [comment]
@f0y the tests are passing on travis but not on appveyor which I believe is because of lack of docker. I tried to install it but it didn't help and it's stuck on "restart required"!

Anyway, please have a look and lemme know if I need to change anything. Here are some stuff that can be improved in my opinion but I leave the judgement to you:

- The database initializer class is not in the prettiest state but it works. It definitely needs a refactor if support of a third database is added.
- The mssql's tests are a copy of postgres' tests. Maybe they shouldn't be copies?

**Comment by f0y** [comment]
@everplays thanks a lot for contribution. I'll add Oracle support and refactor test classes soon.

**Comment by f0y** [comment]
Merged to upstream 81ce35ff5eabb11345771b2d3b3f166c39c1a565

**Pull request closed without merging**
